application: zophop2013
version: testone
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.html

- url: /index\.html
  script: home.app

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$